import type { Metadata } from "next";
import "./globals.css";
import bgImage from "@/assists/bg.png"
import Image from "next/image";
// import { GeistMono } from "geist/font/mono"
import { JetBrains_Mono } from "next/font/google";

const jetBrainsMono = JetBrains_Mono({
  subsets: ["greek"],
  variable: "--font-jetbrains-mono",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        {/* <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link href="https://fonts.googleapis.com/css2?family=Space+Mono:ital,wght@0,400;0,700;1,400;1,700&display=swap" rel="stylesheet" /> */}
      </head>
      <body
        className={`${jetBrainsMono} min-h-screen `}
      >
        <div className="fixed w-full h-full">
          <Image src={bgImage} alt="bgImage" className="w-full h-full object-cover"></Image>
        </div>
        <div className="relative container">
          {children}
        </div>
      </body>
    </html>
  );
}
